### ISSUE TITLE
ICMP checksum

### ISSUE THREAD

**Issue by zhiburt** [coldFireworks/packet_crafter#1]
Hey @coldFireworks, I've bump into this crate with intention to create a simple ping program.
And with a simple framework ~20 lines of code I decided to try to send a echo request where the packet is build in power of this crate. And then I found out that when we change the playground to not standart I it's not working (at least for me) :).

I piled a packet creation to the internals of this https://docs.rs/ping/0.2.0/ping/index.html library and it was fine.

I started investigation according this issue by comparing the buffers. At once I found out that the checksum is different. Then I get the internals of [checksum](https://github.com/coldFireworks/packet_crafter/blob/d832fd04752d84c28c18a50edffd441070fd116a/src/helpers.rs#L46) out and made a compares with internals of the foregoing library. As I can declare the function makes its money.

The issue is in related ti calculation of checksum from its origin.

_As I see we should calculate the checksum not only on header but in awareness of playground too_ [wiki](https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#header_checksum)

When I did this experiment the buffers were equal.

I would create a PR if the changes haven't been going to hurt the core of the library abstractions I suppose.

Thanks.

PS: I am just a regular guy for sure not an expert (So I might am wrong somewhere). I decided to left my observations just in case :).

Example: 

ICMP echo request with the playground filled with 1.

The expectation is based on remote servers responses (`google.com`, `rust-lang.org`, ...). When we use one from expected section we get response in other way not.

```rust
    let mut p = Packet::new(vec![Protocol::ICMP]);
    p.add_header(headers::IcmpHeader::new(8, 0, 0, 0));
    p.extend_payload(vec![1; 24]);

    let buf = p.into_vec();
    println!("{:?}", buf);
```

the result    `[8, 0, 247, 255, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]`
expected     `[8, 0, 235, 243, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]`

**Comment by coldFireworks** [comment]
Thanks for bringing this to my attention! :) you're absolutely right with what you're saying.

I personally never put payload data in ICMP packets so yeah I didn't really think about it.

I've made a commit which should fix it
